@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.sandboxpowered.internal;

import org.sandboxpowered.api.util.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;